version: '3'

services:
  netconf-pnp-simulator:
    image: nexus3.onap.org:10001/onap/integration/simulators/netconf-pnp-simulator:2.8.6
    container_name: netconf-pnp-simulator
    restart: always
    ports:
      - "830:830"
      - "6513:6513"
    volumes:
      - ./:/config/modules

  netconf-pnp-simulator-2:
    image: nexus3.onap.org:10001/onap/integration/simulators/netconf-pnp-simulator:2.8.6
    container_name: netconf-pnp-simulator-2
    restart: always
    ports:
      - "831:830"
      - "6514:6513"
    volumes:
      - ./:/config/modules