version: '3'

services:

  netconf-server:
    container_name: netconf-server
    image: nexus3.onap.org:10003/onap/org.onap.integration.nfsimulator.netconfserver:latest
    environment:
     - ENABLE_TLS=true
    ports:
     - "830:830"
     - "6513:6513"
     - "6555:6555"
