version: '2'
services:
  aai.searchservice.simpledemo.openecomp.org:
    image: ${DOCKER_REGISTRY}/openecomp/search-data-service
    hostname: aai.searchservice.simpledemo.openecomp.org
    container_name: search-service-container
    volumes:
      - ${SEARCH_LOGS}:/logs
      - ./appconfig:/opt/app/search-data-service/config
    ports:
      - 9509:9509
    environment:
      - CONFIG_HOME=/opt/app/search-data-service/config/
      - KEY_STORE_PASSWORD=OBF:1y0q1uvc1uum1uvg1pil1pjl1uuq1uvk1uuu1y10
      - KEY_MANAGER_PASSWORD=OBF:1y0q1uvc1uum1uvg1pil1pjl1uuq1uvk1uuu1y10
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
        
networks:
  default:
      driver: bridge
      driver_opts:
        com.docker.network.driver.mtu: ${MTU}
