server:
    port: 8080
    tomcat:
        max-threads: 50
ssl-enable: false

mso:
  msoKey: 07a7159d3bf51a0e53be7a8f89699be7
  logPath: logs
  site-name: onapheat
  adapters:
    requestDb:
      endpoint: http://request-db-adapter:8083
      auth: Basic YnBlbDpwYXNzd29yZDEk
  catalog:
    db:
      spring:
        endpoint: "http://catalog-db-adapter:8082"
  db:
    auth: Basic YnBlbDpwYXNzd29yZDEk
  config:
    path: /src/main/resources/
  infra:
    default:
      alacarte:
        orchestrationUri: /mso/async/services/ALaCarteOrchestrator
        recipeTimeout: 180
        testApi: VNF_API
      service:
        macro:
          default:
            testApi: GR_API
  camundaURL: http://bpmn-infra:8081
  camundaAuth: 1D9003AB8BAFFA0D2104B67FA89040AD70B5B495B2A5DF931DE236484EBC1681
  async:
    core-pool-size: 50
    max-pool-size: 50
    queue-capacity: 500
  sdc:
    client:
      auth: F3473596C526938329DF877495B494DC374D1C4198ED3AD305EA3ADCBBDA1862
    activate:
      instanceid: test
      userid: cs0008
    endpoint: http://c1.vm1.mso.simpledemo.onap.org:28090
  tenant:
    isolation:
      retry:
        count: 3
  aai:
    endpoint: https://aai.api.simpledemo.onap.org:8443
    auth: 2630606608347B7124C244AB0FE34F6F
  so:
    operational-environment:
      dmaap:
        username: testuser
        password: VjR5NDcxSzA=
        host: http://c1.vm1.mso.simpledemo.onap.org:28090
      publisher:
        topic: com.att.ecomp.mso.operationalEnvironmentEvent

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/catalogdb
    username: cataloguser
    password: catalog123
    driver-class-name: org.mariadb.jdbc.Driver
    dbcp2:
      initial-size: 5
      max-total: 20
      validation-query: select 1
      test-on-borrow: true
  jpa:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: validate
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        enable-lazy-load-no-trans: true
  jersey:
    type: filter

  security:
    usercredentials:
    -
      username: sitecontrol
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: SiteControl-Client
    -
      username: gui
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: GUI-Client
    -
      username: infraportal
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: InfraPortal-Client
    -
      username: InfraPortalClient
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: InfraPortal-Client
    -
      username: bpel
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: BPEL-Client
    -
      username: mso_admin
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: ACTUATOR

request:
  datasource:
    url: jdbc:mariadb://mariadb:3306/requestdb
    username: requestuser
    password: request123
    driver-class-name: org.mariadb.jdbc.Driver
    dbcp2:
      initial-size: 5
      max-total: 20
      validation-query: select 1
      test-on-borrow: true

