spring:
 h2:
  console:
  enabled: true
  path: console
 datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  username: admin
  password: admin
 http:
  converters:
   preferred-json-mapper: gson
 security:
  usercredentials:
   - username: vnfm
     password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
     role: BPEL-Client

server:
  port: 9093
  tomcat:
    max-threads: 50
  ssl:
    client-auth: need
    key-alias: so@so.onap.org
    key--store-password: '7Em3&j4.19xYiMelhD5?xbQ.'
    key-store: classpath:so-vnfm-simulator.p12
    key-store-type: PKCS12
  request:
    grant:
      auth: twowaytls
  dns:
    name: so-vnfm-simulator

vnfds:
  vnfdlist:
  -  vnfdid: sgsn-mme_12df452s04131
     vnfclist:
     - vnfcid: VNFC1
       resourceTemplateId: vnfd1_vnfc1
       vduId: vnfd1_vduForVnfc1
       type: COMPUTE
     - vnfcid: VNFC2
       resourceTemplateId: vnfd1_vnfc2
       vduId: vnfd1_vduForVnfc2
       type: COMPUTE
  -  vnfdid: 2
     vnfclist:
     - vnfcid: VNFC3
       resourceTemplateId: vnfd2_vnfc3
       vduId: vnfd2_vduForVnfc3
       type: COMPUTE
     - vnfcid: VNFC4
       resourceTemplateId: vnfd2_vnfc4
       vduId: vnfd2_vduForVnfc4
       type: COMPUTE
