server:
    port: 8082
    tomcat:
        max-threads: 50
ssl-enable: false
mso:
  logPath: logs
  site-name: onapheat
  catalog:
    db:
      spring:
        endpoint: http://catalog-db-adapter:8082
  db:
    auth: Basic YnBlbDpwYXNzd29yZDEk
spring:
  datasource:
    hikari:
      jdbcUrl: jdbc:mariadb://${DB_HOST}:${DB_PORT}/catalogdb
      username: cataloguser
      password: catalog123
      driver-class-name: org.mariadb.jdbc.Driver
      pool-name: catdb-pool
      registerMbeans: true
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      enable-lazy-load-no-trans: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    usercredentials:
    -
      username: bpel
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: BPEL-Client
    -
      username: mso_admin
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: ACTUATOR

#Actuator
management:
  context-path: /manage

flyway:
  baseline-on-migrate: true
  url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/catalogdb
  user: cataloguser
  password: catalog123
  
cloud_config:
  identity_services:
    DEFAULT_KEYSTONE:
      identity_url: http://192.168.35.52:5000/v2.0
      mso_id: admin
      mso_pass: admin
      admin_tenant: service
      member_role: admin
      tenant_metadata: true
      identity_server_type: KEYSTONE
      identity_authentication_type: USERNAME_PASSWORD
      project_domain_name: service
      user_domain_name: admin
  cloud_sites:
    RegionOne:
      region_id: RegionOne
      clli: RegionOne 
