version: '3'
services:
################################################################################
  mariadb:
    image: mariadb:${MARIADB_VERSION}
################################################################################
  catalog-db-adapter:
    image: onap/so/catalog-db-adapter:${TAG}
################################################################################
  request-db-adapter:
    image: onap/so/request-db-adapter:${TAG}
################################################################################
  sdnc-adapter:
    image: onap/so/sdnc-adapter:${TAG}
################################################################################
  sdc-controller:
    image: onap/so/sdc-controller:${TAG}
################################################################################
  bpmn-infra:
    image: onap/so/bpmn-infra:${TAG}
################################################################################
  api-handler-infra:
    image: onap/so/api-handler-infra:${TAG}
#############################################################################
  so-monitoring:
    image: onap/so/so-monitoring:${TAG}
################################################################################
  so-vnfm-adapter:
    image: onap/so/vnfm-adapter:${SOL_003_ADAPTER_IMAGE_VERSION}
################################################################################
  modeling-etsicatalog:
    image: ${NEXUS_DOCKER_REPO_MSO}/onap/modeling/etsicatalog:${ETSI_CATALOG_IMAGE_VERSION}
################################################################################
  so-etsi-nfvo-ns-lcm:
    image: onap/so/so-etsi-nfvo-ns-lcm:${ETSI_NFVO_NS_LCM_IMAGE_VERSION}
