version: '3'
services:
################################################################################
  sdc-simulator:
    image: simulators/sdc-simulator:latest
    ports:
      - "9991:9991"
    environment:
    - APP=SDC-SIMULATOR
    - JVM_ARGS=-Xms64m -Xmx512m
    hostname:
      sdc-simulator
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
################################################################################
  VNFM-adapter:
    image: nexus3.onap.org:10001/onap/so/vnfm-adapter:1.4.4
    ports:
      - "9092:9092"
    environment:
    - APP=VNFM-adapter
    - JVM_ARGS=-Xms64m -Xmx512m
    hostname:
      vnfm-adapter-test
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
################################################################################

