version: '2.1'
services:
  dfc:
    container_name: dfc
    image: nexus3.onap.org:10001/onap/org.onap.dcaegen2.collectors.datafile.datafile-app-server:latest
    ports:
      - "8433:8433"
    environment:
       CONSUL_HOST: CONSUL_IP
       CONSUL_PORT: 8500
    extra_hosts:
      - "dmaap-dr-node:DR_NODE_IP"