version: '3.3'

services:
  blueprints-processor:
    image: onap/ccsdk-blueprintsprocessor:latest
    ports:
      - "8000:8080"
    restart: always
    container_name: bp-rest
    environment:
      - APPLICATIONNAME=BlueprintsProcessor
      - BUNDLEVERSION=1.0.0
      - APP_CONFIG_HOME=/opt/app/onap/config
      - ENVCONTEXT=dev
    volumes:
      - ${WORKSPACE}/plans/usecases/pnf-sw-upgrade/cds/resources:/opt/app/onap/res
    entrypoint: 
      - /bin/sh
      - -c 
      - "/opt/app/onap/res/importCerAndStartService.sh"
    extra_hosts:
      - sdnc:${LOCAL_IP}
      - db:${LOCAL_IP}
      - aai-simulator:${LOCAL_IP}
