{
    "control_loop_name": "pmsh-control-loop",
    "operational_policy_name": "pmsh-operational-policy",
    "cert_path": "/opt/app/pmsh/etc/certs/cert.pem",
    "enable_tls": true,
    "ca_cert_path": "/opt/app/pmsh/etc/certs/cacert.pem",
    "streams_publishes": {
      "policy_pm_publisher": {
        "dmaap_info": {
          "client_id": "1475976809466",
          "client_role": "org.onap.dcae.pmPublisher",
          "topic_url": "http://mr-sim:3904/events/unauthenticated.DCAE_CL_OUTPUT",
          "location": "san-francisco"
        },
        "type": "message_router"
      }
    },
    "streams_subscribes": {
      "aai_subscriber": {
        "type": "message_router",
        "dmaap_info": {
          "client_id": "1575976809466",
          "client_role": "org.onap.dcae.aaiSub",
          "topic_url": "http://mr-sim:3904/events/AAI-EVENT",
          "location": "san-francisco"
        }
      },
      "policy_pm_subscriber": {
        "dmaap_info": {
          "location": "san-francisco",
          "topic_url": "http://mr-sim:3904/events/unauthenticated.PMSH_CL_INPUT",
          "client_role": "org.onap.dcae.pmSubscriber",
          "client_id": "1575876809456"
        },
        "type": "message_router"
      }
    },
    "key_path": "/opt/app/pmsh/etc/certs/key.pem",
    "aaf_identity": "dcae@dcae.onap.org",
    "aaf_password": "demo123456!"
}