version: '2'
networks:
  dfcnet:
    external:
      name: dfcnet
services:
  dfc:
    #image fron Nexus
    image: nexus3.onap.org:10001/onap/org.onap.dcaegen2.collectors.datafile.datafile-app-server:latest
    #local image for test purposes
    #image: org.onap.dcaegen2.collectors.datafile.datafile-app-server:latest
    container_name: dfc_app0
    ports:
      - "8100:8100"
      - "8433:8433"
    networks:
      dfcnet: null
    volumes:
      - $SIMGROUP_ROOT/tls/:/opt/app/datafile/etc/cert/
    environment:
      CONSUL_HOST: "consul-server"
      CONSUL_PORT: 8500
      CONFIG_BINDING_SERVICE: "config-binding-service"
      CONFIG_BINDING_SERVICE_SERVICE_PORT: 10000
      HOSTNAME: "dfc_app0"
      KNOWN_HOSTS_FILE_PATH: "/home/datafile/.ssh/known_hosts"

