*** Settings ***
Documentation        store all properties that can change or are used in multiple places here
...                    format is all caps with underscores between words and prepended with GLOBAL
...                   make sure you prepend them with GLOBAL so that other files can easily see it is from this file.


*** Variables ***
${GLOBAL_APPLICATION_ID}           robot-ete
${GLOBAL_SELENIUM_BROWSER}        chrome
${GLOBAL_SELENIUM_BROWSER_CAPABILITIES}        Create Dictionary
${GLOBAL_SELENIUM_DELAY}          0
${GLOBAL_SELENIUM_BROWSER_IMPLICIT_WAIT}        5
${GLOBAL_SELENIUM_BROWSER_WAIT_TIMEOUT}        15
${GLOBAL_OPENSTACK_HEAT_SERVICE_TYPE}    orchestration
${GLOBAL_OPENSTACK_CINDER_SERVICE_TYPE}    volume
${GLOBAL_OPENSTACK_NOVA_SERVICE_TYPE}    compute
${GLOBAL_OPENSTACK_NEUTRON_SERVICE_TYPE}    network
${GLOBAL_OPENSTACK_GLANCE_SERVICE_TYPE}    image
${GLOBAL_OPENSTACK_KEYSTONE_SERVICE_TYPE}    identity
${GLOBAL_OPENSTACK_STACK_DEPLOYMENT_TIMEOUT}    600s
${GLOBAL_AAI_CLOUD_OWNER}    CloudOwner
${GLOBAL_AAI_CLOUD_OWNER_DEFINED_TYPE}    OwnerType
${GLOBAL_AAI_COMPLEX_NAME}    clli1
${GLOBAL_AAI_PHYSICAL_LOCATION_ID}    clli1
${GLOBAL_BUILD_NUMBER}    0
${GLOBAL_VID_UI_TIMEOUT_SHORT}    20s
${GLOBAL_VID_UI_TIMEOUT_MEDIUM}    60s
${GLOBAL_VID_UI_TIMEOUT_LONG}    120s
${GLOBAL_VM_PRIVATE_KEY}   ${EXECDIR}/robot/assets/keys/robot_ssh_private_key.pvt
${GLOBAL_AAI_ZONE_ID}    nova1
${GLOBAL_AAI_ZONE_NAME}    nova
${GLOBAL_AAI_DESIGN_TYPE}    integration
${GLOBAL_AAI_ZONE_CONTEXT}    labs
${GLOBAL_AAI_SERVER_PROTOCOL}    http
${GLOBAL_INJECTED_AAI1_IP_ADDR}    localhost
${GLOBAL_AAI_SERVER_PORT}    9900
${GLOBAL_AAI_USERNAME}    test
${GLOBAL_AAI_PASSWORD}    test
${GLOBAL_INJECTED_OPENSTACK_TENANT_ID}    test
${GLOBAL_INJECTED_OPENSTACK_USERNAME}    test
${GLOBAL_INJECTED_OPENSTACK_PASSWORD}    test
${GLOBAL_INJECTED_KEYSTONE}    test
${GLOBAL_PACKET_GENERATOR_PORT}     test
${GLOBAL_PACKET_GENERATOR_USERNAME}       test
${GLOBAL_PACKET_GENERATOR_PASSWORD}     test
${GLOBAL_SERVICE_TEMPLATE_MAPPING}    test
${GLOBAL_DNS_TRAFFIC_DURATION}    test
${GLOBAL_INJECTED_NETWORK}    test
${GLOBAL_SO_SERVER_PROTOCOL}    http
${GLOBAL_INJECTED_SO_IP_ADDR}    localhost
${GLOBAL_SO_SERVER_PORT}    9100
${GLOBAL_SO_ASDC_PORT}    8085
${GLOBAL_SO_CATALOG_PORT}    8082
${GLOBAL_SO_CAMUNDA_PORT}    9200
${GLOBAL_SO_SIMULATOR_PORT}    10000
${resourceLocation}    /app/csar/
${GLOBAL_SO_CATDB_API_URI}    aaaa

${GLOBAL_INJECTED_PROPERTIES}    None
${GLOBAL_INJECTED_ARTIFACTS_VERSION}    None
${GLOBAL_INJECTED_PUBLIC_NET_ID}    None
${GLOBAL_INJECTED_CLOUD_ENV}    None
${GLOBAL_INJECTED_SCRIPT_VERSION}    None
${GLOBAL_INJECTED_VM_IMAGE_NAME}    None
${GLOBAL_INJECTED_VM_FLAVOR}    None
${GLOBAL_PRELOAD_PARAMETERS}    None

${GLOBAL_SDNGC_USERNAME}    admin
${GLOBAL_SDNGC_PASSWORD}    admin
${GLOBAL_SDNGC_SERVER_PROTOCOL}    https
#${GLOBAL_INJECTED_SDNC_IP_ADDR}    
${GLOBAL_INJECTED_SDNC_IP_ADDR}    aaaa
${GLOBAL_SDNGC_REST_PORT}    8443
${GLOBAL_SDNGC_ADMIN_PORT}    8443