version: '3'
services:
################################################################################
  mariadb:
    image: mariadb:10.1.11
################################################################################
  ve-vnfm-adapter:
    image: onap/so/ve-vnfm-adapter
################################################################################
