version: '3.3'

services:
  db:
    container_name: db
    image: nexus3.onap.org:10001/library/postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
    networks:
      net:
        aliases:
        - db

  aai:
    container_name: aai-sim
    image: nexus3.onap.org:10001/mockserver/mockserver:latest
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/aai-initializer.json
      LOG_LEVEL: "DEBUG"
    volumes:
      - ./assets/aai_sim/aai_mockserver.properties:/config/mockserver.properties
      - ./assets/aai_sim/aai-initializer.json:/config/aai-initializer.json
      - ./assets/ssl_certs/mock_server_cacert.pem:/var/tmp/mock_server_cacert.pem
      - ./assets/ssl_certs/mock_server_key.pem:/var/tmp/mock_server_key.pem
    networks:
      net:
        aliases:
        - aai-sim

  mr-sim:
    container_name: mr-sim
    image: nexus3.onap.org:10001/mockserver/mockserver:latest
    command: -logLevel DEBUG -serverPort 3904
    ports:
      - 3904:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/mr-initializer.json
    volumes:
      - ./assets/mr_sim/mr_mockserver.properties:/config/mockserver.properties
      - ./assets/mr_sim/mr-initializer.json:/config/mr-initializer.json
    networks:
      net:
        aliases:
        - mr-sim

  pmsh:
    container_name: pmsh
    image: nexus3.onap.org:10001/onap/org.onap.dcaegen2.services.pmsh:latest
    depends_on:
      - db
    ports:
      - 8443:8443
    volumes:
      - ./assets/ssl_certs/cert.pem:/opt/app/pmsh/etc/certs/cert.pem
      - ./assets/ssl_certs/key.pem:/opt/app/pmsh/etc/certs/key.pem
      - ./assets/ssl_certs/mock_server_cacert.pem:/opt/app/pmsh/etc/certs/cacert.pem
      - ./assets/cbs_sim/application_config.yaml:/app-config/application_config.yaml
    environment:
      HOSTNAME: "dcae-pmsh"
      PMSH_PG_URL: db
      PMSH_PG_USERNAME: $DB_USER
      PMSH_PG_PASSWORD: $DB_PASSWORD
      AAI_SERVICE_PORT: 1080
      DCAE_CA_CERTPATH: '/opt/app/pmsh/etc/certs/cacert.pem'
      CBS_CLIENT_CONFIG_PATH: '/app-config/application_config.yaml'
    networks:
      net:
        aliases:
        - pmsh

networks:
  net:
    driver: bridge

