version: '3.3'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
    networks:
      pmsh-network:

  aai:
    container_name: aai-sim
    image: mockserver/mockserver:mockserver-5.9.0
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/aai-initializer.json
      LOG_LEVEL: "DEBUG"
    volumes:
      - ./assets/aai_sim/aai_mockserver.properties:/config/mockserver.properties
      - ./assets/aai_sim/aai-initializer.json:/config/aai-initializer.json
      - ./assets/ssl_certs/mock_server_cacert.pem:/var/tmp/mock_server_cacert.pem
      - ./assets/ssl_certs/mock_server_key.pem:/var/tmp/mock_server_key.pem
    networks:
      pmsh-network:

  cbs-sim:
    container_name: cbs-sim
    image: mockserver/mockserver:mockserver-5.9.0
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/cbs-initializer.json
      LOG_LEVEL: "DEBUG"
      SERVER_PORT: 10443
    volumes:
      - ./assets/cbs_sim/cbs_mockserver.properties:/config/mockserver.properties
      - ./assets/cbs_sim/cbs-initializer.json:/config/cbs-initializer.json
      - ./assets/ssl_certs/mock_server_cacert.pem:/var/tmp/mock_server_cacert.pem
      - ./assets/ssl_certs/mock_server_key.pem:/var/tmp/mock_server_key.pem
    networks:
      pmsh-network:

  mr-sim:
    container_name: mr-sim
    image: mockserver/mockserver:mockserver-5.9.0
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/mr-initializer.json
      LOG_LEVEL: "DEBUG"
      SERVER_PORT: 3095
    volumes:
      - ./assets/mr_sim/mr_mockserver.properties:/config/mockserver.properties
      - ./assets/mr_sim/mr-initializer.json:/config/mr-initializer.json
    networks:
      pmsh-network:

  pmsh:
    container_name: pmsh
    image: nexus3.onap.org:10001/onap/org.onap.dcaegen2.services.pmsh:latest
    depends_on:
      - db
    volumes:
      - ./assets/ssl_certs/cert.pem:/opt/app/pmsh/etc/certs/cert.pem
      - ./assets/ssl_certs/key.pem:/opt/app/pmsh/etc/certs/key.pem
      - ./assets/ssl_certs/mock_server_cacert.pem:/opt/app/pmsh/etc/certs/cacert.pem
    environment:
      HOSTNAME: "dcae-pmsh"
      CONFIG_BINDING_SERVICE: cbs-sim
      PMSH_PG_URL: db
      PMSH_PG_USERNAME: $DB_USER
      PMSH_PG_PASSWORD: $DB_PASSWORD
      AAI_SERVICE_PORT: 1080
      DCAE_CA_CERTPATH: '/opt/app/pmsh/etc/certs/cacert.pem'
    networks:
      pmsh-network:

networks:
  pmsh-network:
    driver: bridge
