version: '3.3'

services:
  db:
    image: mariadb:latest
    container_name: ccsdk-mariadb
    ports:
      - "3306:3306"
    volumes:
      - ~/vm_mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sdnctl
      MYSQL_DATABASE: sdnctl
      MYSQL_USER: sdnctl
      MYSQL_PASSWORD: sdnctl
  blueprints-processor:
    depends_on:
      - db
    image: onap/ccsdk-blueprintsprocessor:latest
    container_name: bp-rest
    ports:
      - "8000:8080"
    restart: always
    environment:
      - APPLICATIONNAME=BlueprintsProcessor
      - BUNDLEVERSION=1.0.0
      - APP_CONFIG_HOME=/opt/app/onap/config
      - ENVCONTEXT=dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${WORKSPACE}/plans/usecases-config-over-netconf/config-over-netconf/cds/resources:/opt/app/onap/res
    entrypoint:
      - /bin/sh
      - -c
      - "/opt/app/onap/res/importCerAndStartService.sh"
    extra_hosts:
      - sdnc:${LOCAL_IP}

