tosca_definitions_version: tosca_simple_yaml_1_1
metadata:
  invariantUUID: 3fed24ab-7a60-40cd-a52b-520df0d743e8
  UUID: e3334a40-6ede-4d38-975b-705e9cb99d2f
  name: extNeutronCP
  description: The AT&T Connection Point base type all other CP derive from
  type: CP
  category: Generic
  subcategory: Network Elements
  resourceVendor: ONAP (Tosca)
  resourceVendorRelease: 1.0.0.wd03
  resourceVendorModelNumber: ''
imports:
- nodes:
    file: nodes.yml
- datatypes:
    file: data.yml
- capabilities:
    file: capabilities.yml
- relationships:
    file: relationships.yml
- groups:
    file: groups.yml
- policies:
    file: policies.yml
- annotations:
    file: annotations.yml
node_types:
  org.openecomp.resource.cp.v2.extNeutronCP:
    derived_from: org.openecomp.resource.cp.v2.extCP
    description: The AT&T Connection Point base type all other CP derive from
    properties:
      port_security_enabled:
        type: boolean
        description: Flag to enable/disable port security on the network
        required: false
      qos_policy:
        type: string
        description: The name or ID of QoS policy to attach to this network
        required: false
      allowed_address_pairs:
        type: list
        description: Additional MAC/IP address pairs allowed to pass through the port
        required: false
        entry_schema:
          type: org.openecomp.datatypes.heat.network.AddressPair
      binding:vnic_type:
        type: string
        description: The vnic type to be bound on the neutron port
        required: false
      value_specs:
        default: {
          }
        type: map
        description: Extra parameters to include in the request
        required: false
        entry_schema:
          type: string
      related_networks:
        type: list
        description: Related Networks List.
        required: false
        entry_schema:
          type: org.openecomp.datatypes.network.RelatedNetworksAssignments
      network:
        type: string
        description: Network this port belongs to
        required: false
      mac_requirements:
        default:
          mac_count_required:
            is_required: false
        type: org.openecomp.datatypes.network.MacRequirements
        description: identifies MAC address assignments to the CP
        required: false
      mac_address:
        type: string
        description: MAC address to give to this port
        required: false
      ip_range_start:
        type: string
        required: false
      admin_state_up:
        default: true
        type: boolean
        description: A boolean value specifying the administrative status of the network
        required: false
      exCP_naming:
        default:
          ecomp_generated_naming: true
        type: org.openecomp.datatypes.Naming
        required: false
      order:
        type: integer
        description: The order of the CP on the compute instance (e.g. eth2).
        required: true
      subnetpoolid:
        type: string
        required: false
      device_id:
        type: string
        description: Device ID of this port
        required: false
      ip_range_end:
        type: string
        required: false
      ip_address:
        type: string
        required: false
      is_default:
        default: false
        type: boolean
        required: false
      device_owner:
        type: string
        description: Name of the network owning the port
        required: false
      ip_requirements:
        type: list
        description: identifies IP requirements to the CP
        required: true
        entry_schema:
          type: org.openecomp.datatypes.network.IpRequirements
      replacement_policy:
        default: AUTO
        type: string
        description: Policy on how to respond to a stack-update for this resource
        required: false
      network_role:
        type: string
        description: identical to VL network_role
        required: true
      security_groups:
        type: list
        description: List of security group names or IDs
        required: false
        entry_schema:
          type: string
      fixed_ips:
        type: list
        description: Desired IPs for this port
        required: false
        entry_schema:
          type: org.openecomp.datatypes.heat.neutron.port.FixedIps
      subinterface_indicator:
        default: false
        type: boolean
        description: identifies if Port is having Sub Interface
        required: false
      name:
        type: string
        description: A symbolic name for this port
        required: false
      vlan_requirements:
        type: list
        description: identifies vlan address assignments to the CP
        required: false
        entry_schema:
          type: org.openecomp.datatypes.network.VlanRequirements
      network_role_tag:
        type: string
        description: Must correlate to the set of defined network-role tag identifiers from the associated HEAT template
        required: true
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
    capabilities:
      attachment:
        type: tosca.capabilities.Attachment
        occurrences:
        - 1
        - UNBOUNDED
        valid_source_types: [
          ]
      binding:
        type: tosca.capabilities.network.Bindable
        occurrences:
        - 0
        - UNBOUNDED
        valid_source_types:
        - org.openecomp.resource.cp.nodes.heat.network.contrailV2.VLANSubInterface
        - org.openecomp.resource.cp.nodes.heat.network.v2.contrailV2.VLANSubInterface
